# POSTGRES DB: CLIENT
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-client
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-client
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-db-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-client
  template:
    metadata:
      labels:
        app: db-client
    spec:
      containers:
        - name: db-client
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "db_grpc_client"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: db-client-storage
              mountPath: /var/lib/postgresql/client-data
      volumes:
        - name: db-client-storage
          persistentVolumeClaim:
            claimName: pvc-db-client
---
apiVersion: v1
kind: Service
metadata:
  name: db-client
  labels:
    app: db-client
spec:
  selector:
    app: db-client
  ports:
    - name: db-client
      port: 5432
      targetPort: 5432
---
# POSTGRES DB: TRANSACTION
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-transaction
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db-transaction
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-transaction
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-db-transaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-transaction
  labels:
    app: db-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-transaction
  template:
    metadata:
      labels:
        app: db-transaction
    spec:
      containers:
        - name: db-transaction
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: "db_grpc_transaction"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: db-transaction-storage
              mountPath: /var/lib/postgresql/transaction-data
      volumes:
        - name: db-transaction-storage
          persistentVolumeClaim:
            claimName: pvc-db-transaction
---
apiVersion: v1
kind: Service
metadata:
  name: db-transaction
  labels:
    app: db-transaction
spec:
  selector:
    app: db-transaction
  ports:
    - name: db-transaction
      port: 5432
      targetPort: 5432