services:
  client_grpc_server:
    build:
      context: .
      dockerfile: ./src/clientServer/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db_client:
        condition: service_healthy
    networks:
      - transactions_manager_network
    env_file:
      - ./src/clientServer/.env
  transaction_grpc_server:
    build:
      context: .
      dockerfile: ./src/transactionServer/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      db_transaction:
        condition: service_healthy
    networks:
      - transactions_manager_network
    env_file:
      - ./src/transactionServer/.env

  db_client:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_grpc_client
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_grpc_client"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transactions_manager_network
    volumes:
      - db_client_data:/var/lib/postgresql/client_data

  db_transaction:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_grpc_transaction
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_grpc_transaction"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transactions_manager_network
    volumes:
      - db_transaction_data:/var/lib/postgresql/transaction_data

networks:
  transactions_manager_network:
    name: transactions_manager_network
volumes:
  db_client_data:
  db_transaction_data: