# SERVICE: gRPC CLIENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-grpc-server
  labels:
    app: client-grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-grpc-server
      app: client-grpc-server
  template:
    metadata:
      labels:
        name: client-grpc-server
        app: client-grpc-server
    spec:
      containers:
        - name: client-grpc-server
          image: lipeaaraujo/client-grpc-server
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: CLIENT_DB_URL
              value: "postgres://user:12345@db-client:5432/db_client"
            - name: GRPC_CLIENT_PORT
              value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: client-grpc-server
  labels:
    app: client-grpc-server
spec:
  selector:
    app: client-grpc-server
  ports:
    - name: client-grpc-server
      port: 4000
      targetPort: 4000

---
# SERVICE: gRPC TRANSACTION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-grpc-server
  labels:
    app: transaction-grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: transaction-grpc-server
      app: transaction-grpc-server
  template:
    metadata:
      labels:
        name: transaction-grpc-server
        app: transaction-grpc-server
    spec:
      containers:
        - name: transaction-grpc-server
          image: lipeaaraujo/transaction-grpc-server
          ports:
            - containerPort: 4001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: TRANSACTION_DB_URL
              value: "postgres://user:12345@db-transaction:5432/db_transaction"
            - name: GRPC_TRANSACTIONS_PORT
              value: "4001"
            - name: GRPC_CLIENT_URL
              value: "client-grpc-server:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-grpc-server
  labels:
    app: transaction-grpc-server
spec:
  selector:
    app: transaction-grpc-server
  ports:
    - name: transaction-grpc-server
      port: 4001
      targetPort: 4001
---
# SERVICE: WEB SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-grpc-server
  labels:
    app: web-grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web-grpc-server
      app: web-grpc-server
  template:
    metadata:
      labels:
        name: web-grpc-server
        app: web-grpc-server
    spec:
      containers:
        - name: web-grpc-server
          image: lipeaaraujo/grpc-web-server
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: GRPC_TRANSACTION_URL
              value: "transaction-grpc-server:4001"
            - name: GRPC_CLIENT_URL
              value: "client-grpc-server:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: web-grpc-server
  labels:
    app: web-grpc-server
spec:
  selector:
    app: web-grpc-server
  ports:
    - name: web-grpc-server
      port: 8080
      targetPort: 8080