apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: web-grpc-server
    release: prometheus
  name: web-grpc-server-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: web-grpc-server
  endpoints:
    - port: web-grpc-server
      path: /metrics
      interval: 15s
