apiVersion: v1
kind: Service
metadata:
  name: client-grpc-server
  labels:
    app: client-grpc-server
spec:
  selector:
    app: client-grpc-server
  ports:
    - name: grpc
      port: 4000
      targetPort: 4000
    - name: metrics
      port: 9100
      targetPort: 9100