services:
  client_rest_server:
    build:
      context: .
      dockerfile: ./clientServer/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      rest_db_client:
        condition: service_healthy
    networks:
      - transactions_manager_rest_network
  transaction_rest_server:
    build:
      context: .
      dockerfile: ./transactionServer/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      rest_db_transaction:
        condition: service_healthy
    networks:
      - transactions_manager_rest_network

  rest_db_client:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_client
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_client"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transactions_manager_rest_network
    volumes:
      - db_client_data:/var/lib/postgresql/client_data

  rest_db_transaction:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_transaction
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_transaction"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transactions_manager_rest_network
    volumes:
      - db_transaction_data:/var/lib/postgresql/transaction_data

networks:
  transactions_manager_rest_network:
    name: transactions_manager_rest_network
volumes:
  db_client_data:
  db_transaction_data: